language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: hhvm
        - php: nightly

    allow_failures:
        - php: hhvm
        - php: nightly

    fast_finish: true

services:
  - memcached
  - redis-server

before_script:
    - sh -c "if [[ $TRAVIS_PHP_VERSION != 'hhvm' && `php-config --vernum` -ge 50500 ]] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install apcu ; else echo 'extension="apc.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;fi"
    - if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
    - if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then echo "apc.enabled=1\n" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
    - if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then echo "apc.enable_cli=1\n" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
    - composer self-update
    - composer global require --prefer-source phpunit/phpunit:"^4.8 || 5.3.*" satooshi/php-coveralls:^1.0.0
    - composer install --prefer-source
    - mkdir -p ./build/logs

script:
    - ~/.composer/vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml

after_script:
    - 'echo ''coverage_clover: build/logs/clover.xml'' >> ./.coveralls.yml'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ~/.composer/vendor/bin/coveralls -v; fi;'

notifications:
    email: false
