language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
    global:
        - MIN_PHP=5.6.0

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: hhvm-stable
        - php: nightly

    allow_failures:
        - php: hhvm-stable
        - php: nightly

    fast_finish: true

services:
  - memcached
  - redis-server

before_install:
    - PHP=$TRAVIS_PHP_VERSION
    - if [[ ! $PHP = hhvm* ]]; then INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; else INI_FILE=/etc/hhvm/php.ini; fi

    - if [[ ! $skip ]]; then echo opcache.enable_cli = 1 >> $INI_FILE; fi

    - if [[ ! $skip && $PHP = 5.* ]]; then (echo yes | pecl install -f apcu-4.0.11 && echo apc.enable_cli = 1 >> $INI_FILE); fi
    - if [[ ! $skip && $PHP = 7.* ]]; then (echo yes | pecl install -f apcu-5.1.6 && echo apc.enable_cli = 1 >> $INI_FILE); fi

    - if [[ ! $skip && $PHP = 5.* ]]; then echo extension = memcached.so >> $INI_FILE; fi

before_script:
    - composer self-update
    - composer global require --prefer-source phpunit/phpunit:"^5.7" satooshi/php-coveralls:^1.0.0
    - composer install --prefer-source
    - mkdir -p ./build/logs

script:
    - ~/.composer/vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml

after_script:
    - 'echo ''coverage_clover: build/logs/clover.xml'' >> ./.coveralls.yml'
    - if [[ $PHP = 5.* || $PHP = 7.* ]]; then php ~/.composer/vendor/bin/coveralls -v; fi

notifications:
    email: false
