language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
        - php: 7.0
        - php: 7.1
        - php: nightly

    allow_failures:
        - php: nightly

    fast_finish: true

services:
  - memcached
  - redis-server

before_install:
    - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

    - echo opcache.enable_cli = 1 >> $INI_FILE
    - echo yes | pecl install -f apcu-5.1.6 && echo apc.enable_cli = 1 >> $INI_FILE
    - echo extension = memcached.so >> $INI_FILE

before_script:
    - composer self-update
    - composer global require --prefer-source phpunit/phpunit:"6.2.*" satooshi/php-coveralls:^1.0.0
    - composer install --prefer-source
    - mkdir -p ./build/logs

script:
    - ~/.composer/vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml

after_script:
    - 'echo ''coverage_clover: build/logs/clover.xml'' >> ./.coveralls.yml'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ~/.composer/vendor/bin/coveralls -v; fi;'

notifications:
    email: false
